# development:
#    stripe_secret_key:  'sk_test_51KdArQSBdSS02xMTGL0MjofCekgvjSG6fVvsnkW0xxMrGfQ8sUhwsiB1y9HFkJL18KuR0AapcOAsX53pLZqadl6r00jyqZ3iny'
#      stripe_publishable_key: 'pk_test_51KdArQSBdSS02xMTLBEh5nmCDrK2TznkjHnhh7Jc3MYFiN2Eri6AWH9XK14WykZDROwNiOREgDBAnPRsKROV8k0400qwSqYBAB'

# production:
#   stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
#   stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'

#      